---
language: php
php:
- 5.3
- 5.4
- 5.5
before_script:
#- sudo apt-get install -qq expect graphviz libmagickwand-dev
#- expect tools/build/tools.expect
#- pear channel-discover pear.phpunit.de
#- pear channel-discover pear.pdepend.org
#- pear channel-discover pear.phpmd.org
- pear channel-discover pear.phpdoc.org
#- pear channel-discover pear.phpqatools.org
#- pear install -f phpunit/PHPUnit
#- pear install -f phpunit/DbUnit
#- pear install -f phpunit/FinderFacade
#- pear install -f phpunit/PHPUnit_Selenium
#- pear install -f phpunit/PHPUnit_Story
#- pear install -f phpunit/PHP_Invoker
- pear install -f phpdoc/phpDocumentor-alpha
#- pear install -f --alldeps pear/PHP_CodeSniffer
#- pear install -f phpqatools/PHP_CodeBrowser
#- pear install -f pdepend/PHP_Depend
#- pear install -f phpmd/PHP_PMD
#- pear install -f phpunit/phpdcd
#- pear install -f phpunit/phploc
#- pear install -f phpunit/phpcpd
- phpenv rehash
- composer self-update
- composer install

matrix:
  allow_failures:
  - php: 5.5
script:
- ant travis -Dphpunit.testdox=true
- bin/behat -c tests/behat.yml

after_success: ./tools/build/update-gh-pages.sh

env:
  global:
  - secure: |-
      mXV3RbUlgDSt6tRvOhkbERypbTF29ceqDWtwNmw/gXvqcteH4HqOKJZoUcqO
      keS1zZ2PrnG0OD2/9Fy6GGoQ9Y2gS9bIsdD2RJJLjg6ueG6jc4nIU2jywlNC
      ZprS+6Z91rtQ/peF4wvOgAxliGvzlgc8am4MGPu1oPU0LQ9WN+w=
