---
language: php
php:
- 5.3
- 5.4
- 5.5
before_script:
- sudo apt-get install -qq expect graphviz libmagickwand-dev
- expect tools/build/tools.expect
- phpenv rehash
- composer self-update
- composer install

matrix:
  allow_failures:
  - php: 5.5
script:
- ant travis -Dphpunit.testdox=true

after_success: ./build/tools/update-gh-pages.sh

env:
  global:
  - secure: |-
      mXV3RbUlgDSt6tRvOhkbERypbTF29ceqDWtwNmw/gXvqcteH4HqOKJZoUcqO
      keS1zZ2PrnG0OD2/9Fy6GGoQ9Y2gS9bIsdD2RJJLjg6ueG6jc4nIU2jywlNC
      ZprS+6Z91rtQ/peF4wvOgAxliGvzlgc8am4MGPu1oPU0LQ9WN+w=
